name: Ruby Gem

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    container: ruby:2.6
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Bundle
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Test
      run: |
        bundle exec rake test
      env:
        REDIS_HOST: redis
        REDIS_PORT: 6379

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Bundle
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        rake release
      env:
        GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
